# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(763, 574)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 901, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_despoblacion = QtWidgets.QLabel(self.tab)
        self.label_despoblacion.setGeometry(QtCore.QRect(30, 50, 161, 16))
        self.label_despoblacion.setObjectName("label_despoblacion")
        self.label_seleccionar_algoritmo = QtWidgets.QLabel(self.tab)
        self.label_seleccionar_algoritmo.setGeometry(QtCore.QRect(30, 170, 141, 16))
        self.label_seleccionar_algoritmo.setObjectName("label_seleccionar_algoritmo")
        self.lineEdit_despoblacion = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_despoblacion.setGeometry(QtCore.QRect(210, 50, 301, 20))
        self.lineEdit_despoblacion.setReadOnly(True)
        self.lineEdit_despoblacion.setObjectName("lineEdit_despoblacion")
        self.pushButton_abrir_despoblacion = QtWidgets.QPushButton(self.tab)
        self.pushButton_abrir_despoblacion.setGeometry(QtCore.QRect(560, 50, 75, 23))
        self.pushButton_abrir_despoblacion.setObjectName("pushButton_abrir_despoblacion")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(210, 170, 301, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.pushButton_ejecutar = QtWidgets.QPushButton(self.tab)
        self.pushButton_ejecutar.setGeometry(QtCore.QRect(550, 160, 111, 41))
        self.pushButton_ejecutar.setObjectName("pushButton_ejecutar")
        self.textBrowser_resultado = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_resultado.setGeometry(QtCore.QRect(30, 230, 641, 221))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_resultado.setFont(font)
        self.textBrowser_resultado.setObjectName("textBrowser_resultado")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_noticias_clasificar = QtWidgets.QLabel(self.tab_2)
        self.label_noticias_clasificar.setGeometry(QtCore.QRect(20, 30, 141, 16))
        self.label_noticias_clasificar.setObjectName("label_noticias_clasificar")
        self.label_modelo_clasificador = QtWidgets.QLabel(self.tab_2)
        self.label_modelo_clasificador.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.label_modelo_clasificador.setObjectName("label_modelo_clasificador")
        self.lineEdit_noticias_clasificar = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_noticias_clasificar.setGeometry(QtCore.QRect(160, 30, 401, 20))
        self.lineEdit_noticias_clasificar.setReadOnly(True)
        self.lineEdit_noticias_clasificar.setObjectName("lineEdit_noticias_clasificar")
        self.pushButton_modelo_clasificador = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_modelo_clasificador.setGeometry(QtCore.QRect(590, 70, 111, 41))
        self.pushButton_modelo_clasificador.setObjectName("pushButton_modelo_clasificador")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 671, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.comboBox_modelos = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_modelos.setGeometry(QtCore.QRect(160, 80, 401, 22))
        self.comboBox_modelos.setObjectName("comboBox_modelos")
        self.label_score = QtWidgets.QLabel(self.tab_2)
        self.label_score.setGeometry(QtCore.QRect(20, 140, 131, 16))
        self.label_score.setObjectName("label_score")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_despoblacion.setText(_translate("MainWindow", " Ruta noticias entrenamiento"))
        self.label_seleccionar_algoritmo.setText(_translate("MainWindow", "Seleccionar algoritmo:"))
        self.lineEdit_despoblacion.setText(_translate("MainWindow", "Ruta"))
        self.pushButton_abrir_despoblacion.setText(_translate("MainWindow", "Abrir"))
        self.pushButton_ejecutar.setText(_translate("MainWindow", "EJECUTAR"))
        self.textBrowser_resultado.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">Resultado:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Entrenamiento"))
        self.label_noticias_clasificar.setText(_translate("MainWindow", "Noticias para clasificar: "))
        self.label_modelo_clasificador.setText(_translate("MainWindow", "Modelo clasificador:"))
        self.lineEdit_noticias_clasificar.setText(_translate("MainWindow", "Ruta"))
        self.pushButton_modelo_clasificador.setText(_translate("MainWindow", "PREDECIR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Noticia"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etiqueta"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ruta noticia"))
        self.label_score.setText(_translate("MainWindow", "Score:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Clasificación"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

